### PR TITLE
Adding audio capability to ffmpeg_source

### PR DESCRIPTION
**Pull request by alokmahor**

### CODE REVIEW

**Comment by hrueger** [comment]
Wow, very cool! Thanks @alokmahor 
How do you know that? Do you know what other options can be set?

**Comment by alokmahor** [comment]
I was also looking for that so today I debugged Streamlabs OBS there I found
https://github.com/stream-labs/streamlabs-obs/blob/32d2e5bc3b107bf4e39880300f4a4d9c8ba620ee/app/services/audio/audio.ts#L222

**Comment by alokmahor** [comment]
possible values of `monitoringType` are 0, 1, 2
`0` means `Monitor Off`
`1` means `Monitor only(mute output)`
`2` means `Monitor and Output`
By default value is 0. for getting audio we can set value 1 or 2

**Comment by hrueger** [comment]
closred in favor of #39

**Pull request closed without merging**
